[build]
  base = "morphy/"
  publish = "morphy/build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "14.17.2"
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.10"
