[build]
  base = "./"
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "14.17.2"
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.10"
  DISABLE_ESLINT_PLUGIN = "true"
  TSC_COMPILE_ON_ERROR = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
