export default {
  concisePositions: [
    [['bk', 'b4']],
    [
      ['wq', 'e2'],
      ['wk', 'f2'],
      ['bq', 'h8'],
      ['bk', 'h7'],
    ],
    [
      ['wr', 'a1'],
      ['wn', 'b1'],
      ['wb', 'c1'],
      ['wq', 'd1'],
      ['wk', 'e1'],
      ['wb', 'f1'],
      ['wn', 'g1'],
      ['wr', 'h1'],
      ['wp', 'a2'],
      ['wp', 'b2'],
      ['wp', 'c2'],
      ['wp', 'd2'],
      ['wp', 'e2'],
      ['wp', 'f2'],
      ['wp', 'g2'],
      ['wp', 'h2'],

      ['bp', 'a7'],
      ['bp', 'b7'],
      ['bp', 'c7'],
      ['bp', 'd7'],
      ['bp', 'e7'],
      ['bp', 'f7'],
      ['bp', 'g7'],
      ['bp', 'h7'],
      ['br', 'a8'],
      ['bn', 'b8'],
      ['bb', 'c8'],
      ['bq', 'd8'],
      ['bk', 'e8'],
      ['bb', 'f8'],
      ['bn', 'g8'],
      ['br', 'h8'],
    ],
  ],
  concisePositionResults: [
    [undefined, {}, {}, {}, { b: { type: 'k', color: 'b' } }, {}, {}, {}, {}],
    [
      undefined,
      {},
      { e: { type: 'q', color: 'w' }, f: { type: 'k', color: 'w' } },
      {},
      {},
      {},
      {},
      { h: { type: 'k', color: 'b' } },
      { h: { type: 'q', color: 'b' } },
    ],
    [
      undefined,
      {
        a: { type: 'r', color: 'w' },
        b: { type: 'n', color: 'w' },
        c: { type: 'b', color: 'w' },
        d: { type: 'q', color: 'w' },
        e: { type: 'k', color: 'w' },
        f: { type: 'b', color: 'w' },
        g: { type: 'n', color: 'w' },
        h: { type: 'r', color: 'w' },
      },
      {
        a: { type: 'p', color: 'w' },
        b: { type: 'p', color: 'w' },
        c: { type: 'p', color: 'w' },
        d: { type: 'p', color: 'w' },
        e: { type: 'p', color: 'w' },
        f: { type: 'p', color: 'w' },
        g: { type: 'p', color: 'w' },
        h: { type: 'p', color: 'w' },
      },
      {},
      {},
      {},
      {},
      {
        a: { type: 'p', color: 'b' },
        b: { type: 'p', color: 'b' },
        c: { type: 'p', color: 'b' },
        d: { type: 'p', color: 'b' },
        e: { type: 'p', color: 'b' },
        f: { type: 'p', color: 'b' },
        g: { type: 'p', color: 'b' },
        h: { type: 'p', color: 'b' },
      },
      {
        a: { type: 'r', color: 'b' },
        b: { type: 'n', color: 'b' },
        c: { type: 'b', color: 'b' },
        d: { type: 'q', color: 'b' },
        e: { type: 'k', color: 'b' },
        f: { type: 'b', color: 'b' },
        g: { type: 'n', color: 'b' },
        h: { type: 'r', color: 'b' },
      },
    ],
  ],
};
