import {
  createBoard,
  createFromConcisePosition,
} from '../../../utils/board/boardEditor';
import { BoardAndMoves } from '../common.test.utils';

export const pureQueenPositionAndMoves: BoardAndMoves[] = [
  {
    board: createBoard({
      position: createFromConcisePosition({
        wq: ['d5'],
      }),
    }),
    testPieceSquare: 'd5',
    expectedMoves: [
      'd1',
      'h1',
      'a2',
      'd2',
      'g2',
      'b3',
      'd3',
      'f3',
      'c4',
      'd4',
      'e4',
      'e5',
      'f5',
      'g5',
      'h5',
      'c5',
      'b5',
      'a5',
      'c6',
      'd6',
      'e6',
      'b7',
      'd7',
      'f7',
      'a8',
      'd8',
      'g8',
    ],
  },
  {
    board: createBoard({
      position: createFromConcisePosition({
        bq: ['d5'],
      }),
      state: { turn: 'b' },
    }),
    testPieceSquare: 'd5',
    expectedMoves: [
      'd1',
      'h1',
      'a2',
      'd2',
      'g2',
      'b3',
      'd3',
      'f3',
      'c4',
      'd4',
      'e4',
      'e5',
      'f5',
      'g5',
      'h5',
      'c5',
      'b5',
      'a5',
      'c6',
      'd6',
      'e6',
      'b7',
      'd7',
      'f7',
      'a8',
      'd8',
      'g8',
    ],
  },
];
