name: Pull Request CI - Morphy

on:
  pull_request:
    branches:
      - master
    paths:
      - 'morphy/**'

jobs:
  quality_assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 14.x
          registry-url: https://registry.npmjs.org
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: cd morphy/
        name: Change to web-ui directory
      - run: yarn install --frozen-lockfile
      - name: Format
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Dependency Cruiser
        run: yarn cruise-deps
      - name: Tests
        run: yarn test
